import{a as _,S as q,i as a}from"./assets/vendor-DqqeFO82.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",$="50868712-4e51c6fc19c53f8b926e21bf1";async function f(o,t=1){return(await _.get(B,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const M=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");function g(o){const t=o.map(({webformatURL:e,largeImageURL:r,tags:s,likes:L,views:v,comments:w,downloads:S})=>`
          <li class="gallery-item">
            <a href="${r}" class="gallery__link">
              <img src="${e}" alt="${s}" class="gallery__image" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${L}</p>
              <p><b>Views:</b> ${v}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${S}</p>
            </div>
          </li>
        `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function x(){M.innerHTML=""}function p(){m.classList.remove("is-hidden")}function h(){m.classList.add("is-hidden")}function C(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}function O(){const o=document.querySelector(".gallery .gallery__image");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}const u=document.querySelector(".form"),P=document.querySelector(".load-more");let i="",n=1,d=0;u.addEventListener("submit",async o=>{if(o.preventDefault(),x(),b(),i=u.elements["search-text"].value.trim(),n=1,!i){a.warning({message:"Введіть пошуковий запит."});return}p();try{const t=await f(i,n);if(d=t.totalHits,t.hits.length===0){a.info({message:"Нічого не знайдено. Спробуйте інше слово."});return}g(t.hits),d>15&&C()}catch{a.error({message:"Сталася помилка під час запиту."})}finally{h()}});P.addEventListener("click",async()=>{n+=1,p();try{const o=await f(i,n);g(o.hits),O(),n*15>=d&&(b(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Не вдалося отримати наступні зображення."})}finally{h()}});
//# sourceMappingURL=index.js.map
